### PR TITLE
[02-Git] Mordyk Alex

### PR DESCRIPTION
**Pull request by kurtwalkir**
Hi Andriy. Sorry for delay. Yesterday I was invited to this course. Pls check and let me know if I did something wrong. Thank you.
 
**Description:**
The console game a rock-paper-scissors.

**Installation:**
**Ubuntu dependency's:**
**g++ & Make :** sudo apt-get install build-essential
**Pthread- :** sudo apt-get install libpthread-stubs0-dev

**Usage:**
./game

### CODE REVIEW

**Review by an1kh — CHANGES_REQUESTED** [review]
Could you please split the code into several sequential commits?
Also fix the commit title: use Implement instead of ImplementED

**Comment by kurtwalkir** [comment]
Hi Andriy. Thank you for your feedback. Fixed the commit with wrong title. Also added a few new commits with minor bug fixes and new features.

**Review by an1kh — CHANGES_REQUESTED** [review]
Please squash the commits 2 and 2 with the 1st one because they are fixes to unmerged patch.
e.g. git rebase -i ...:
pick Git-02: Implement simple game 
squash Git-02: Fix makefile 
squash Git-02: Add destructor 

The resulting branch with 2 commits will be okay.

**Comment by kurtwalkir** [comment]
Hi Andriy. Figured out with the  git rebase -i ... and have completed your last task. Thank you.

**Review by an1kh — APPROVED** [review]
Well done! Please merge

**Pull request merged**
